const materialUi = [
  'autocomplete',
  'button',
  'button group',
  'checkbox',
  'floating action button',
  'radio button',
  'rating',
  'select',
  'slider',
  'switch',
  'text field',
  'transfer list',
  'toggle button',
  'avatar',
  'badge',
  'chip',
  'divider',
  'icons',
  'material icons',
  'list',
  'table',
  'tooltip',
  'typography',
  'alert',
  'backdrop',
  'dialog',
  'progress',
  'skeleton',
  'snackbar',
  'accordion',
  'app bar',
  'card',
  'paper',
  'bottom navigation',
  'breadcrumbs',
  'drawer',
  'link',
  'menu',
  'pagination',
  'speed dial',
  'stepper',
  'tabs',
  'box',
  'container',
  'grid',
  'stack',
  'image list',
  'hidden',
  'click-away listener',
  'css baseline',
  'modal',
  'no ssr',
  'popover',
  'popper',
  'portal',
  'textarea autosize',
  'transitions',
  'usemediaquery',
  'data grid',
  'date & time pickers',
  'masonry',
  'timeline',
  'tree view',
];
